apiVersion: v1
name: prometheus
version: 9.1.0
appVersion: 2.11.1
description: Prometheus is a monitoring system and time series database.
home: https://prometheus.io/
icon: file://../logo.png
sources:
  - https://github.com/prometheus/alertmanager
  - https://github.com/prometheus/prometheus
  - https://github.com/prometheus/pushgateway
  - https://github.com/prometheus/node_exporter
  - https://github.com/kubernetes/kube-state-metrics
maintainers:
  - name: mgoodness
    email: mgoodness@gmail.com
  - name: gianrubio
    email: gianrubio@gmail.com
engine: gotpl
tillerVersion: ">=2.8.0"
