## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    dnsmasq:
      port: 10054
    skydns: 
      port: 10055

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}
