## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    port: 10251

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}

prometheusRule:
  ## Custom Labels to be added to PrometheusRule
  ##
  labels: {}
