level: cluster

enabledRBAC: true

## Already exist ServiceAccount
##
serviceAccountName: ""

enabledPSP: true

## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Node labels for Grafana pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: {}
  #  - key: "key"
  #    operator: "Equal"
  #    value: "value"
  #    effect: "NoSchedule"

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}

## Pass extra environment variables to the Grafana container.
##
# extraVars:
# - name: EXTRA_VAR_1
#   value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2
extraVars:

adminUser: "admin"
adminPassword: "admin"

## Grafana Docker image
##
image:
  repository: grafana/grafana
  tag: 5.3.0
  inits:
    tools:
      repository: maiwj/curl
      tag: 7.56.1-r0

storageSpec: {}
#   storageClassName: default
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 2Gi
#   selector: {}

## Easy way to create persistent data
##
persistence: {}
#  enabled: true
#  storageClass: gluster
#  accessMode: "ReadWriteOnce"
#  size: 50Gi

## Resource limits & requests
## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  inits:
    limits:
      memory: 50Mi
      cpu: 50m
    requests:
      memory: 50Mi
      cpu: 50m
  core:
    limits:
      memory: 200Mi
      cpu: 200m
    requests:
      memory: 100Mi
      cpu: 100m
  proxy:
    limits:
      memory: 100Mi
      cpu: 100m
    requests:
      memory: 50Mi
      cpu: 50m
  watcher:
    limits:
      memory: 50Mi
      cpu: 50m
    requests:
      memory: 50Mi
      cpu: 50m


## A list of additional configmaps that contain -dashboard.json and/or -datasource.json files
## that should be imported into grafana.
dashboardConfigmaps: []

prometheusDatasourceURL: ""

grafanaProxy:
  repository: nginx
  tag: 1.15.2

grafanaWatcher:
  repository: quay.io/coreos/grafana-watcher
  tag: v0.0.8

  ## Resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  resources: {}
    #requests:
    #  memory: "16Mi"
    #  cpu: "50m"
    #limits:
    #  memory: "32Mi"
    #  cpu: "100m"
