## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Skip verification until we have resolved why the certificate validation
## for the kubelet on API server nodes fail.
##
insecureSkipVerify: true

## TLS Cofiguration for the service monitor, default to none, but append cert and keyfile if passed
##
caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
certFile: ""
keyFile: ""

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    scheme: "https"
    port: 4001

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}
