{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: expose-operator-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    monitoring.cattle.io: "true"
spec:
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: http
{{- end }}