apiVersion: {{ template "operator_api_version" . }}
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    {{- if .Values.prometheusRule.labels }}
{{ toYaml .Values.prometheusRule.labels | indent 4 }}
    {{- end }}
  name: {{ template "app.fullname" . }}
spec:
  groups:
  - name: kubernetes.rules
    rules:
    - record: pod_name:container_memory_usage_bytes:sum
      expr: sum(container_memory_usage_bytes{container_name!="POD",pod_name!=""}) BY
        (pod_name)
    - record: pod_name:container_spec_cpu_shares:sum
      expr: sum(container_spec_cpu_shares{container_name!="POD",pod_name!=""}) BY (pod_name)
    - record: pod_name:container_cpu_usage:sum
      expr: sum(rate(container_cpu_usage_seconds_total{container_name!="POD",pod_name!=""}[5m]))
        BY (pod_name)
    - record: pod_name:container_fs_usage_bytes:sum
      expr: sum(container_fs_usage_bytes{container_name!="POD",pod_name!=""}) BY (pod_name)
    - record: namespace:container_memory_usage_bytes:sum
      expr: sum(container_memory_usage_bytes{container_name!=""}) BY (namespace)
    - record: namespace:container_spec_cpu_shares:sum
      expr: sum(container_spec_cpu_shares{container_name!=""}) BY (namespace)
    - record: namespace:container_cpu_usage:sum
      expr: sum(rate(container_cpu_usage_seconds_total{container_name!="POD"}[5m]))
        BY (namespace)
    - record: cluster:memory_usage:ratio
      expr: sum(container_memory_usage_bytes{container_name!="POD",pod_name!=""}) BY
        (cluster) / sum(machine_memory_bytes) BY (cluster)
    - record: cluster:container_spec_cpu_shares:ratio
      expr: sum(container_spec_cpu_shares{container_name!="POD",pod_name!=""}) / 1000
        / sum(machine_cpu_cores)
    - record: cluster:container_cpu_usage:ratio
      expr: sum(rate(container_cpu_usage_seconds_total{container_name!="POD",pod_name!=""}[5m]))
        / sum(machine_cpu_cores)
    - record: apiserver_latency_seconds:quantile
      expr: histogram_quantile(0.99, rate(apiserver_request_latencies_bucket[5m])) /
        1e+06
      labels:
        quantile: "0.99"
    - record: apiserver_latency:quantile_seconds
      expr: histogram_quantile(0.9, rate(apiserver_request_latencies_bucket[5m])) /
        1e+06
      labels:
        quantile: "0.9"
    - record: apiserver_latency_seconds:quantile
      expr: histogram_quantile(0.5, rate(apiserver_request_latencies_bucket[5m])) /
        1e+06
      labels:
        quantile: "0.5"
