apiVersion: v1
description: EFK(Elasticsearch + Fluentd + Kibana)
name: efk
version: 7.6.2
appVersion: 7.6.2
icon: file://../efk-logo.jpg
sources:
- https://www.elastic.co/products/elasticsearch
- https://www.elastic.co/products/kibana
- https://fluentd.io/
home: https://www.elastic.co
maintainers:
- name: guangbochen
  email: support@rancher.com
engine: gotpl
