dependencies:
  - name: elasticsearch
    version: 7.6.3
    condition: elasticsearch.enabled
  - name: kibana
    version: 7.6.3
    condition: kibana.enabled
    repository: file://./charts/kibana
  - name: fluentd-elasticsearch
    version: 9.3.1
    condition: fluentd-elasticsearch.enabled
    repository: file://./charts/fluentd-elasticsearch
