enabledRBAC: true

## Already exist ServiceAccount
##
serviceAccountName: ""

## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Expertor listens on where and exports on host
##
ports: 
  metrics:
    port: 9100

# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/prometheus/node-exporter
  tag: v0.16.0

resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi

container:
  args:
  - --path.procfs=/host/proc
  - --path.sysfs=/host/sys

  volumes:
  - name: proc
    hostPath:
      path: /proc
  - name: sys
    hostPath:
      path: /sys

  volumeMounts:
  - name: proc
    mountPath: /host/proc
    readOnly:  true
  - name: sys
    mountPath: /host/sys
    readOnly: true

## Tolerations for use with node taints
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations:
- effect: NoSchedule
  operator: Exists

## Node Selector to constrain pods to run on particular nodes
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
##
nodeSelector: {}

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}

prometheusRule:
  ## Custom Labels to be added to PrometheusRule
  ##
  labels: {}

