apiVersion: v1
kind: Service
metadata:
  name:   expose-node-metrics
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    monitoring.cattle.io: "true"
spec:
  type: ClusterIP
  selector:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    release: {{ .Release.Name }}
  ports:
  - name: metrics
    port: {{ .Values.ports.metrics.port }}
    targetPort: {{ .Values.ports.metrics.port }}
    protocol: TCP
