apiVersion: {{ template "deployment_api_version" . }}
kind: Deployment
metadata:
  name: {{ template "app.nginx.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      chart: {{ template "app.version" . }}
      release: {{ .Release.Name }}
      component: nginx
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
        component: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.2
        args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /nginx/nginx.conf
        volumeMounts:
        - mountPath: /nginx/
          name: alertmanager-nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      volumes:
      - name: alertmanager-nginx
        configMap:
          defaultMode: 438
          items:
          - key: nginx.conf
            mode: 438
            path: nginx.conf
          name: {{ template "app.nginx.fullname" . }}