kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-cfs-throttled-seconds-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU cfs throttled
  description: container cpu cfs throttled seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-cfs-throttled-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU cfs throttled([[container_name]])
  description: container cpu cfs throttled seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-usage-seconds-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: container-cpu-usage
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_usage_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU usage
  description: container cpu usage seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-usage-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: container-cpu-usage
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_usage_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU usage([[container_name]])
  description: container cpu usage seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-system-seconds-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_system_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU system seconds
  description: container cpu system seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-system-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_system_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU system seconds([[container_name]])
  description: container cpu system seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-user-seconds-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_user_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU user seconds
  description: container cpu user seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-cpu-user-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_user_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)
  legendFormat: CPU user seconds([[container_name]])
  description: container cpu user seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-memory-usage-percent
  labels:
    app: metric-expression
    component: container
    details: "false"
    level: project
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~"$namespace",
    pod=~"$podName", container=~"$containerName"},"container_name", "", "container"))
    by (container_name)
  legendFormat: Memory
  description: container memory usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-memory-usage-percent-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    level: project
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~"$namespace",
    pod=~"$podName", container=~"$containerName"},"container_name", "", "container"))
    by (container_name)
  legendFormat: Memory([[container_name]])
  description: container memory usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-memory-usage-bytes-sum
  labels:
    app: metric-expression
    component: container
    details: "false"
    level: project
    metric: memory-usage-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{name!~"POD", namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name)
  legendFormat: Memory usage
  description: container memory usage bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-memory-usage-bytes-sum-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    level: project
    metric: memory-usage-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{name!~"POD", namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name)
  legendFormat: Memory usage([[container_name]])
  description: container memory usage bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-fs-bytes-sum
  labels:
    app: metric-expression
    component: container
    details: "false"
    level: project
    metric: fs-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_fs_usage_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name)
  legendFormat: Filesystem usage
  description: container fs bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-fs-bytes-sum-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    level: project
    metric: fs-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_fs_usage_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name=~"$containerName"}) by (container_name)
  legendFormat: Filesystem usage([[container_name]])
  description: container fs bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-disk-io-writes-bytes-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: disk-io
    level: project
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_writes_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name) * 8 / 1024
  legendFormat: Write
  description: container disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-disk-io-writes-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: disk-io
    level: project
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_writes_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name) * 8 / 1024
  legendFormat: Write([[container_name]])
  description: container disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-disk-io-reads-bytes-sum-rate
  labels:
    app: metric-expression
    component: container
    details: "false"
    graph: disk-io
    level: project
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_reads_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)  * 8 / 1024
  legendFormat: Read
  description: container disk io reads bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: container-disk-io-reads-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: container
    details: "true"
    graph: disk-io
    level: project
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_reads_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name=~"$containerName"}[5m])) by (container_name)  * 8 / 1024
  legendFormat: Read([[container_name]])
  description: container disk io reads bytes sum rate
---
