kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-reading
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="reading"})
  legendFormat: Reading connections
  description: ingresscontroller nginx connection reading
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-reading-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="reading"}) by (instance)
  legendFormat: Reading connections
  description: ingresscontroller nginx connection reading
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-waiting
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="waiting"})
  legendFormat: Nginx waiting connection
  description: ingresscontroller nginx connection waiting
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-waiting-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="waiting"}) by (instance)
  legendFormat: Nginx waiting connection
  description: ingresscontroller nginx connection waiting
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-writing
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="writing"})
  legendFormat: Writing connections
  description: ingresscontroller nginx connection writing
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-writing-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="writing"}) by (instance)
  legendFormat: Writing connections
  description: ingresscontroller nginx connection writing
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-accepted
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="accepted"})
  legendFormat: Accepted connections
  description: ingresscontroller nginx connection accepted
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-accepted-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="accepted"}) by (instance)
  legendFormat: Accepted connections
  description: ingresscontroller nginx connection accepted
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-active
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="active"})
  legendFormat: Active connections
  description: ingresscontroller nginx connection active
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-active-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="active"}) by (instance)
  legendFormat: Active connections
  description: ingresscontroller nginx connection active
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-handled
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="handled"})
  legendFormat: Handled connections
  description: ingresscontroller nginx connection handled
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-connection-handled-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    graph: nginx-connection
    level: cluster
    source: rancher-monitoring
spec:
  expression: sum(nginx_connections{state="handled"}) by (instance)
  legendFormat: Handled connections
  description: ingresscontroller nginx connection handled
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-upstream-response-seconds-by-host
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    level: cluster
    metric: upstream-response-seconds
    source: rancher-monitoring
spec:
  expression: sort_desc(max(upstream_response_time_seconds_sum) by (host, path))
  legendFormat: Upstream response seconds(host:[[host]] path:[[path]])
  description: ingresscontroller nginx upstream response seconds by host
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-upstream-response-seconds-by-host-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    level: cluster
    metric: upstream-response-seconds
    source: rancher-monitoring
spec:
  expression: sort_desc(max(upstream_response_time_seconds_sum) by (host, path))
  legendFormat: Upstream response seconds(host:[[host]] path:[[path]])
  description: ingresscontroller nginx upstream response seconds by host
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-process-seconds-by-path
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "false"
    level: cluster
    metric: request-process-seconds
    source: rancher-monitoring
spec:
  expression: max(request_duration_seconds_bucket{le="1"}) by (host, path)
  legendFormat: Request duration(host:[[host]] path:[[path]])
  description: ingresscontroller nginx request duration by path
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: ingresscontroller-nginx-process-seconds-by-path-details
  labels:
    app: metric-expression
    component: ingresscontroller
    details: "true"
    level: cluster
    metric: request-process-seconds
    source: rancher-monitoring
spec:
  expression: max(request_duration_seconds_bucket{le="1"}) by (host, path)
  legendFormat: Request duration(host:[[host]] path:[[path]])
  description: ingresscontroller nginx request duration by path
---
