kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-disk-io-reads-bytes-sum-rate
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: disk-io
    level: cluster
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(node_disk_read_bytes_total[5m])) by
    () * 8 / 1024
  legendFormat: Read
  description: cluster disk io reads bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-disk-io-reads-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: disk-io
    level: cluster
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(node_disk_read_bytes_total[5m])) by
    (instance) * 8 / 1024
  legendFormat: Read([[instance]])
  description: cluster disk io reads bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-bytes-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-io
    level: cluster
    metric: network-transmit-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_bytes_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
     * 8 / 1024
  legendFormat: Transmit
  description: cluster network transmit bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-bytes-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-io
    level: cluster
    metric: network-transmit-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_bytes_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance) * 8 / 1024
  legendFormat: Transmit([[instance]])
  description: cluster network transmit bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-5
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: cpu-load
    level: cluster
    metric: cpu-load-5
    source: rancher-monitoring
spec:
  expression: sum(node_load5)  / count(node_cpu_seconds_total{mode="system"})
    
  legendFormat: Load5
  description: cluster cpu load 5
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-5-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: cpu-load
    level: cluster
    metric: cpu-load-5
    source: rancher-monitoring
spec:
  expression: sum(node_load5) by (instance) / count(node_cpu_seconds_total{mode="system"})
    by (instance)
  legendFormat: Load5([[instance]])
  description: cluster cpu load 5
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-1
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: cpu-load
    level: cluster
    metric: cpu-load-1
    source: rancher-monitoring
spec:
  expression: sum(node_load1)  / count(node_cpu_seconds_total{mode="system"})
    
  legendFormat: Load1
  description: cluster cpu load 1
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-1-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: cpu-load
    level: cluster
    metric: cpu-load-1
    source: rancher-monitoring
spec:
  expression: sum(node_load1) by (instance) / count(node_cpu_seconds_total{mode="system"})
    by (instance)
  legendFormat: Load1([[instance]])
  description: cluster cpu load 1
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-disk-io-writes-bytes-sum-rate
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: disk-io
    level: cluster
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(node_disk_written_bytes_total[5m]))
     * 8 / 1024
  legendFormat: Write
  description: cluster disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-disk-io-writes-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: disk-io
    level: cluster
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(node_disk_written_bytes_total[5m]))
    by (instance) * 8 / 1024
  legendFormat: Write([[instance]])
  description: cluster disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-fs-usage-percent
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    level: cluster
    metric: fs-usage-percent
    source: rancher-monitoring
spec:
  expression: (sum(node_filesystem_size_bytes{device!="rootfs"})
     - sum(node_filesystem_free_bytes{device!="rootfs"})
    ) / sum(node_filesystem_size_bytes{device!="rootfs"})
    
  legendFormat: Disk usage
  description: cluster fs usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-fs-usage-percent-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    level: cluster
    metric: fs-usage-percent
    source: rancher-monitoring
spec:
  expression: (sum(node_filesystem_size_bytes{device!="rootfs"})
    by (instance) - sum(node_filesystem_free_bytes{device!="rootfs"})
    by (instance)) / sum(node_filesystem_size_bytes{device!="rootfs"})
    by (instance)
  legendFormat: '[[instance]]'
  description: cluster fs usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-errors-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-receive-errors-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_errs_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Receive errors
  description: cluster network receive errors sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-errors-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-receive-errors-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_errs_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Receive errors([[instance]])
  description: cluster network receive errors sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-15
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: cpu-load
    level: cluster
    metric: cpu-load-15
    source: rancher-monitoring
spec:
  expression: sum(node_load15)  / count(node_cpu_seconds_total{mode="system"})
    
  legendFormat: Load15
  description: cluster cpu load 15
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-load-15-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: cpu-load
    level: cluster
    metric: cpu-load-15
    source: rancher-monitoring
spec:
  expression: sum(node_load15) by (instance) / count(node_cpu_seconds_total{mode="system"})
    by (instance)
  legendFormat: Load15([[instance]])
  description: cluster cpu load 15
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-bytes-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-io
    level: cluster
    metric: network-receive-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_bytes_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
     * 8 / 1024
  legendFormat: Receive
  description: cluster network receive bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-bytes-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-io
    level: cluster
    metric: network-receive-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_bytes_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance) * 8 / 1024
  legendFormat: Receive([[instance]])
  description: cluster network receive bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-packets-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-receive-packets-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_packets_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Receive packets
  description: cluster network receive packets sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-packets-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-receive-packets-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_packets_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Receive packets([[instance]])
  description: cluster network receive packets sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-errors-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-transmit-errors-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_errs_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Transmit errors
  description: cluster network transmit errors sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-errors-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-transmit-errors-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_errs_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Transmit errors([[instance]])
  description: cluster network transmit errors sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-packets-dropped-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-receive-packets-dropped-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_drop_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Receive dropped
  description: cluster network receive packets dropped sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-receive-packets-dropped-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-receive-packets-dropped-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_receive_drop_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Receive dropped([[instance]])
  description: cluster network receive packets dropped sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-packets-dropped-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-transmit-packets-dropped-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_drop_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Transmit dropped
  description: cluster network transmit packets dropped sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-packets-dropped-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-transmit-packets-dropped-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_drop_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Transmit dropped([[instance]])
  description: cluster network transmit packets dropped sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-packets-sum
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    graph: network-packet
    level: cluster
    metric: network-transmit-packets-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_packets_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    
  legendFormat: Transmit packets
  description: cluster network transmit packets sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-network-transmit-packets-sum-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    graph: network-packet
    level: cluster
    metric: network-transmit-packets-sum
    source: rancher-monitoring
spec:
  expression: sum(rate(node_network_transmit_packets_total{device!~"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*"}[5m]))
    by (instance)
  legendFormat: Transmit packets([[instance]])
  description: cluster network transmit packets sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-usage-seconds-sum-rate
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    level: cluster
    metric: cpu-usage-seconds-sum-rate
    source: rancher-monitoring
spec:
  expression: 1 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])))
  legendFormat: CPU usage
  description: cluster cpu usage seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-cpu-usage-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    level: cluster
    metric: cpu-usage-seconds-sum-rate
    source: rancher-monitoring
spec:
  expression: 1 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) by (instance))
  legendFormat: '[[instance]]'
  description: cluster cpu usage seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-memory-usage-percent
  labels:
    app: metric-expression
    component: cluster
    details: "false"
    level: cluster
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: 1 - sum(node_memory_MemAvailable_bytes) 
    / sum(node_memory_MemTotal_bytes) 
  legendFormat: Memory usage
  description: cluster memory usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: cluster-memory-usage-percent-details
  labels:
    app: metric-expression
    component: cluster
    details: "true"
    level: cluster
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: 1 - sum(node_memory_MemAvailable_bytes) by (instance)
    / sum(node_memory_MemTotal_bytes) by (instance)
  legendFormat: '[[instance]]'
  description: cluster memory usage percent
---
