kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: input-record-number
  labels:
    app: metric-expression
    component: fluentd
    details: "false"
    level: cluster
    metric: input-record
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_input_status_num_records_total[5m])) 
  legendFormat: Input record number
  description: Fluentd input status num records total
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: input-record-number-details
  labels:
    app: metric-expression
    component: fluentd
    details: "true"
    level: cluster
    metric: input-record
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_input_status_num_records_total[5m])) by (instance)
  legendFormat: Input record number([[instance]])
  description: Fluentd input status num records total
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: output-record-number
  labels:
    app: metric-expression
    component: fluentd
    details: "false"
    level: cluster
    metric: output-record
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_num_records_total[5m])) 
  legendFormat: Output record number
  description: Fluentd output status num records total
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: output-record-number-details
  labels:
    app: metric-expression
    component: fluentd
    details: "true"
    level: cluster
    metric: output-record
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_num_records_total[5m])) by (instance)
  legendFormat: Output record number([[instance]])
  description: Fluentd output status num records total
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: output-errors
  labels:
    app: metric-expression
    component: fluentd
    details: "false"
    level: cluster
    metric: output-errors
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_num_errors[5m])) 
  legendFormat: Plugin Output errors
  description: Fluentd output errors number
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: output-errors-details
  labels:
    app: metric-expression
    component: fluentd
    details: "true"
    level: cluster
    metric: output-errors
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_num_errors[5m])) by (type)
  legendFormat: Plugin([[type]])
  description: Fluentd output errors number
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: buffer-queue-length
  labels:
    app: metric-expression
    component: fluentd
    details: "false"
    level: cluster
    metric: buffer-queue-length
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_buffer_queue_length[5m])) 
  legendFormat: Buffer queue
  description: Fluentd Buffer queue length
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: buffer-queue-length-details
  labels:
    app: metric-expression
    component: fluentd
    details: "true"
    level: cluster
    metric: buffer-queue-length
    source: rancher-monitoring
spec:
  expression: sum(rate(fluentd_output_status_buffer_queue_length[5m])) by (instance)
  legendFormat: '[[instance]]'
  description: Fluentd Buffer queue length
---
