kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-cfs-throttled-seconds-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: CPU cfs throttled
  description: pod cpu cfs throttled seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-cfs-throttled-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_cfs_throttled_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: CPU cfs throttled([[container_name]])
  description: pod cpu cfs throttled seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-memory-usage-percent
  labels:
    app: metric-expression
    component: pod
    details: "false"
    level: project
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name!=""})  / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~"$namespace",
    pod=~"$InstanceName"},"pod_name", "", "pod")) 
  legendFormat: Memory
  description: pod memory usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-memory-usage-percent-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    level: project
    metric: memory-usage-percent
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name!=""}) by (container_name) / sum(label_join(kube_pod_container_resource_limits_memory_bytes{namespace=~"$namespace",
    pod=~"$InstanceName"},"pod_name", "", "pod")) by (container_name)
  legendFormat: Memory([[container_name]])
  description: pod memory usage percent
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-fs-bytes-sum
  labels:
    app: metric-expression
    component: pod
    details: "false"
    level: project
    metric: fs-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_fs_usage_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name!=""}) 
  legendFormat: Filesystem usage
  description: pod fs bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-fs-bytes-sum-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    level: project
    metric: fs-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_fs_usage_bytes{namespace=~"$namespace", pod_name=~"$podName",
    container_name!=""}) by (container_name)
  legendFormat: Filesystem usage([[container_name]])
  description: pod fs bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-packets-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-receive-packets-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_packets_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Receive packets
  description: pod network receive packets sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-packets-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-receive-packets-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_packets_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Receive packets([[container_name]])
  description: pod network receive packets sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-packets-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-transmit-packets-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_packets_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Transmit packets
  description: pod network transmit packets sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-packets-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-transmit-packets-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_packets_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Transmit packets([[container_name]])
  description: pod network transmit packets sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-user-seconds-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_user_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: CPU user seconds
  description: pod cpu user seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-user-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_user_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: CPU user seconds([[container_name]])
  description: pod cpu user seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-disk-io-reads-bytes-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: disk-io
    level: project
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_reads_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m]))   * 8 / 1024
  legendFormat: Read
  description: pod disk io reads bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-disk-io-reads-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: disk-io
    level: project
    metric: disk-io-reads-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_reads_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)  * 8 / 1024
  legendFormat: Read([[container_name]])
  description: pod disk io reads bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-bytes-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-io
    level: project
    metric: network-receive-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m]))  * 8 / 1024
  legendFormat: Receive
  description: pod network receive bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-io
    level: project
    metric: network-receive-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name) * 8 / 1024
  legendFormat: Receive
  description: pod network receive bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-bytes-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-io
    level: project
    metric: network-transmit-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m]))  * 8 / 1024
  legendFormat: Transmit
  description: pod network transmit bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-io
    level: project
    metric: network-transmit-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name) * 8 / 1024
  legendFormat: Transmit
  description: pod network transmit bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-packets-dropped-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-receive-packets-dropped-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_packets_dropped_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Receive dropped
  description: pod network receive packets dropped sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-packets-dropped-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-receive-packets-dropped-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_packets_dropped_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Receive dropped
  description: pod network receive packets dropped sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-memory-usage-bytes-sum
  labels:
    app: metric-expression
    component: pod
    details: "false"
    level: project
    metric: memory-usage-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{name!~"POD", namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}) 
  legendFormat: Memory usage
  description: pod memory usage bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-memory-usage-bytes-sum-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    level: project
    metric: memory-usage-bytes-sum
    source: rancher-monitoring
spec:
  expression: sum(container_memory_working_set_bytes{name!~"POD", namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}) by (container_name)
  legendFormat: Memory usage([[container_name]])
  description: pod memory usage bytes sum
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-disk-io-writes-bytes-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: disk-io
    level: project
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_writes_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m]))  * 8 / 1024
  legendFormat: Write
  description: pod disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-disk-io-writes-bytes-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: disk-io
    level: project
    metric: disk-io-writes-bytes-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_fs_writes_bytes_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name) * 8 / 1024
  legendFormat: Write([[container_name]])
  description: pod disk io writes bytes sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-errors-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-receive-errors-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_errors_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Receive errors
  description: pod network receive errors sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-receive-errors-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-receive-errors-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_receive_errors_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Receive errors
  description: pod network receive errors sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-usage-seconds-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: container-cpu-usage
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_usage_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: CPU usage
  description: pod CPU usage sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-usage-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: container-cpu-usage
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_usage_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: CPU usage([[container_name]])
  description: pod CPU usage sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-errors-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-transmit-errors-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_errors_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Transmit errors
  description: pod network transmit errors sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-errors-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-transmit-errors-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_errors_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Transmit errors
  description: pod network transmit errors sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-packets-dropped-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: network-packet
    level: project
    metric: network-transmit-packets-dropped-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_packets_dropped_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: Transmit dropped
  description: pod network transmit packets dropped sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-network-transmit-packets-dropped-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: network-packet
    level: project
    metric: network-transmit-packets-dropped-sum-rate
    source: rancher-monitoring
spec:
  expression: sum(rate(container_network_transmit_packets_dropped_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: Transmit dropped
  description: pod network transmit packets dropped sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-system-seconds-sum-rate
  labels:
    app: metric-expression
    component: pod
    details: "false"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_system_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) 
  legendFormat: CPU system seconds
  description: pod cpu system seconds sum rate
---
kind: MonitorMetric
apiVersion: management.cattle.io/v3
metadata:
  name: pod-cpu-system-seconds-sum-rate-details
  labels:
    app: metric-expression
    component: pod
    details: "true"
    graph: container-cpu-usage-details
    level: project
    source: rancher-monitoring
spec:
  expression: sum(rate(container_cpu_system_seconds_total{namespace=~"$namespace",pod_name=~"$podName",
    container_name!=""}[5m])) by (container_name)
  legendFormat: CPU system seconds([[container_name]])
  description: pod cpu system seconds sum rate
---
