---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-server-leader-sum
spec:
  resourceType: etcd
  priority: 200
  title: etcd-server-leader-sum
  description: etcd server leader sum
  metricsSelector:
    details: "false"
    component: etcd
    metric: server-leader-sum
  detailsMetricsSelector:
    details: "true"
    component: etcd
    metric: server-leader-sum
  yAxis:
    unit: number
  graphType: singlestat
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-server-failed-proposal
spec:
  resourceType: etcd
  priority: 201
  title: etcd-server-failed-proposal
  description: etcd server failed proposal
  metricsSelector:
    details: "false"
    component: etcd
    metric: server-failed-proposal
  detailsMetricsSelector:
    details: "true"
    component: etcd
    metric: server-failed-proposal
  yAxis:
    unit: number
  graphType: singlestat
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-leader-change
spec:
  resourceType: etcd
  priority: 202
  title: etcd-leader-change
  description: etcd leader change
  metricsSelector:
    details: "false"
    component: etcd
    metric: server-leader-changes-seen-sum-increase
  detailsMetricsSelector:
    details: "true"
    component: etcd
    metric: server-leader-changes-seen-sum-increase
  yAxis:
    unit: number
  graphType: singlestat
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-grpc-client
spec:
  resourceType: etcd
  priority: 203
  title: etcd-grpc-client
  description: etcd grpc client receive/send bytes sum rate
  metricsSelector:
    details: "false"
    component: etcd
    graph: rpc-client-traffic
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: rpc-client-traffic
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
    metric: db-bytes-sum 
  name: etcd-db-bytes-sum
spec:
  resourceType: etcd
  priority: 204
  title: etcd-db-bytes-sum
  description: etcd db bytes sum
  metricsSelector:
    details: "false"
    component: etcd
    metric: db-bytes-sum 
  detailsMetricsSelector:
    details: "true"
    component: etcd
    metric: db-bytes-sum 
  yAxis:
    unit: byte
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-stream
spec:
  resourceType: etcd
  priority: 205
  title: etcd-stream
  description: Etcd lease/watch stream
  metricsSelector:
    details: "false"
    component: etcd
    graph: etcd-stream
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: etcd-stream
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-peer-traffic
spec:
  resourceType: etcd
  priority: 206
  title: etcd-peer-traffic
  description: Etcd peer traffic in/out
  metricsSelector:
    details: "false"
    component: etcd
    graph: etcd-peer-traffic
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: etcd-peer-traffic
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-raft-proposals
spec:
  resourceType: etcd
  priority: 207
  title: etcd-raft-proposals
  description: Etcd raft proposals
  metricsSelector:
    details: "false"
    component: etcd
    graph: proposal
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: proposal
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-rpc-rate
spec:
  resourceType: etcd
  priority: 208
  title: etcd-rpc-rate
  description: Etcd rpc-rate
  metricsSelector:
    details: "false"
    component: etcd
    graph: rpc-rate
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: rpc-rate
  yAxis:
    unit: ops
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-disk-operate
spec:
  resourceType: etcd
  priority: 209
  title: etcd-disk-operate
  description: Etcd disk operate
  metricsSelector:
    details: "false"
    component: etcd
    graph: disk-operate
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: disk-operate
  yAxis:
    unit: seconds
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: etcd
  name: etcd-sync-duration
spec:
  resourceType: etcd
  priority: 209
  title: etcd-sync-duration
  description: Etcd sync-duration
  metricsSelector:
    details: "false"
    component: etcd
    graph: sync-duration
  detailsMetricsSelector:
    details: "true"
    component: etcd
    graph: sync-duration
  yAxis:
    unit: seconds