apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-cpu-usage
spec:
  resourceType: node
  priority: 500
  title: node-cpu-usage
  metricsSelector:
    details: "false"
    component: node
    metric: cpu-usage-seconds-sum-rate
  detailsMetricsSelector:
    details: "true"
    component: node
    metric: cpu-usage-seconds-sum-rate
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-cpu-load
spec:
  resourceType: node
  priority: 501
  title: node-cpu-load
  metricsSelector:
    details: "false"
    component: node
    graph: cpu-load
  detailsMetricsSelector:
    details: "true"
    component: node
    graph: cpu-load
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-memory-usage
spec:
  resourceType: node
  priority: 502
  title: node-memory-usage
  metricsSelector:
    details: "false"
    component: node
    metric: memory-usage-percent
  detailsMetricsSelector:
    details: "true"
    component: node
    metric: memory-usage-percent
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-fs-usage-percent
spec:
  resourceType: node
  priority: 503
  title: node-fs-usage-percent
  thresholds: 10
  metricsSelector:
    details: "false"
    component: node
    metric: fs-usage-percent
  detailsMetricsSelector:
    details: "true"
    component: node
    metric: fs-usage-percent
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-disk-io
spec:
  resourceType: node
  priority: 504
  title: node-disk-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: node
    graph: disk-io
  detailsMetricsSelector:
    details: "true"
    component: node
    graph: disk-io
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-network-io
spec:
  resourceType: node
  priority: 505
  title: node-network-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: node
    graph: network-io
  detailsMetricsSelector:
    details: "true"
    component: node
    graph: network-io
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: node
  name: node-network-packet
spec:
  resourceType: node
  priority: 506
  title: node-network-packet
  thresholds: 10
  metricsSelector:
    details: "false"
    component: node
    graph: network-packet
  detailsMetricsSelector:
    details: "true"
    component: node
    graph: network-packet
  yAxis:
    unit: pps