---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: controllermanager
    cluster-graph: kube-component
  name: controllermanager-queue-depth
spec:
  resourceType: controllermanager
  displayResourceType: kube-component
  priority: 310
  title: controllermanager-queue-depth
  metricsSelector:
    details: "false"
    component: controllermanager
  detailsMetricsSelector:
    details: "true"
    component: controllermanager
  yAxis:
    unit: number
