apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: ingresscontroller
    cluster-graph: kube-component
  name: ingresscontroller-nginx-connection
spec:
  resourceType: ingresscontroller
  displayResourceType: kube-component
  priority: 330
  title: ingresscontroller-nginx-connection
  metricsSelector:
    details: "false"
    component: ingresscontroller
    graph: nginx-connection
  detailsMetricsSelector:
    details: "true"
    component: ingresscontroller
    graph: nginx-connection
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: ingresscontroller
    cluster-graph: kube-component
  name: ingresscontroller-request-process-time
spec:
  resourceType: ingresscontroller
  displayResourceType: kube-component
  priority: 331
  title: ingresscontroller-request-process-time
  metricsSelector:
    details: "false"
    component: ingresscontroller
    metric: request-process-seconds
  detailsMetricsSelector:
    details: "true"
    component: ingresscontroller
    metric: request-process-seconds
  yAxis:
    unit: seconds
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: ingresscontroller
    cluster-graph: kube-component
  name: ingresscontroller-upstream-response-seconds
spec:
  resourceType: ingresscontroller
  displayResourceType: kube-component
  priority: 332
  title: ingresscontroller-upstream-response-seconds
  metricsSelector:
    details: "false"
    component: ingresscontroller
    metric: upstream-response-seconds
  detailsMetricsSelector:
    details: "true"
    component: ingresscontroller
    metric: upstream-response-seconds
  yAxis:
    unit: seconds
  graphType: singlestat