apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-cpu-usage
spec:
  resourceType: cluster
  priority: 100
  title: cluster-cpu-usage
  metricsSelector:
    details: "false"
    component: cluster
    metric: cpu-usage-seconds-sum-rate
  detailsMetricsSelector:
    details: "true"
    component: cluster
    metric: cpu-usage-seconds-sum-rate
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-cpu-load
spec:
  resourceType: cluster
  priority: 101
  title: cluster-cpu-load
  metricsSelector:
    details: "false"
    component: cluster
    graph: cpu-load
  detailsMetricsSelector:
    details: "true"
    component: cluster
    graph: cpu-load
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-memory-usage
spec:
  resourceType: cluster
  priority: 102
  title: cluster-memory-usage
  metricsSelector:
    details: "false"
    component: cluster
    metric: memory-usage-percent
  detailsMetricsSelector:
    details: "true"
    component: cluster
    metric: memory-usage-percent
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-fs-usage-percent
spec:
  resourceType: cluster
  priority: 103
  title: cluster-fs-usage-percent
  thresholds: 10
  metricsSelector:
    details: "false"
    component: cluster
    metric: fs-usage-percent
  detailsMetricsSelector:
    details: "true"
    component: cluster
    metric: fs-usage-percent
  yAxis:
    unit: percent
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-disk-io
spec:
  resourceType: cluster
  priority: 104
  title: cluster-disk-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: cluster
    graph: disk-io
  detailsMetricsSelector:
    details: "true"
    component: cluster
    graph: disk-io
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-network-io
spec:
  resourceType: cluster
  priority: 105
  title: cluster-network-io
  thresholds: 10
  metricsSelector:
    details: "false"
    component: cluster
    graph: network-io
  detailsMetricsSelector:
    details: "true"
    component: cluster
    graph: network-io
  yAxis:
    unit: kbps
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: cluster
  name: cluster-network-packet
spec:
  resourceType: cluster
  priority: 106
  title: cluster-network-packet
  thresholds: 10
  metricsSelector:
    details: "false"
    component: cluster
    graph: network-packet
  detailsMetricsSelector:
    details: "true"
    component: cluster
    graph: network-packet
  yAxis:
    unit: pps