## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    port: 9153

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}
