apiVersion: {{ template "operator_api_version" . }}
kind: PrometheusRule
metadata:
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    source: rancher-monitoring
    {{- if .Values.prometheusRule.labels }}
{{ toYaml .Values.prometheusRule.labels | indent 4 }}
    {{- end }}   
  name: {{ template "app.fullname" . }}
spec:
  groups:
  - name: kube-scheduler.rules
    rules:
    - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
      expr: histogram_quantile(0.99, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.99"
    - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
      expr: histogram_quantile(0.9, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.9"
    - record: cluster:scheduler_e2e_scheduling_latency_seconds:quantile
      expr: histogram_quantile(0.5, sum(scheduler_e2e_scheduling_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.5"
    - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
      expr: histogram_quantile(0.99, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.99"
    - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
      expr: histogram_quantile(0.9, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.9"
    - record: cluster:scheduler_scheduling_algorithm_latency_seconds:quantile
      expr: histogram_quantile(0.5, sum(scheduler_scheduling_algorithm_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.5"
    - record: cluster:scheduler_binding_latency_seconds:quantile
      expr: histogram_quantile(0.99, sum(scheduler_binding_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.99"
    - record: cluster:scheduler_binding_latency_seconds:quantile
      expr: histogram_quantile(0.9, sum(scheduler_binding_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.9"
    - record: cluster:scheduler_binding_latency_seconds:quantile
      expr: histogram_quantile(0.5, sum(scheduler_binding_latency_microseconds_bucket)
        BY (le, cluster)) / 1e+06
      labels:
        quantile: "0.5"
