## CRD apiGroup
##
apiGroup: "monitoring.coreos.com"

## Skip verification until we have resolved why the certificate validation
## for the kubelet on API server nodes fail.
##
insecureSkipVerify: true

## Custom endpoints
##
endpoints: []

ports: 
  metrics:
    port: 10252

serviceMonitor:
  ## Custom Labels to be added to ServiceMonitor
  ##
  labels: {}
