dependencies:
  - name: alertmanager
    version: 0.0.1
    condition: alertmanager.enabled
    repository: "file://./charts/alertmanager/"

  - name: exporter-coredns
    version: 0.0.1
    condition: exporter-coredns.enabled
    repository: "file://./charts/exporter-coredns/"

  - name: exporter-kube-controller-manager
    version: 0.0.1
    condition: exporter-kube-controller-manager.enabled
    repository: "file://./charts/exporter-kube-controller-manager/"

  - name: exporter-kube-dns
    version: 0.0.1
    condition: exporter-kube-dns.enabled
    repository: "file://./charts/exporter-kube-dns/"

  - name: exporter-kube-etcd
    version: 0.0.1
    condition: exporter-kube-etcd.enabled
    repository: "file://./charts/exporter-kube-etcd/"

  - name: exporter-kube-scheduler
    version: 0.0.1
    condition: exporter-kube-scheduler.enabled
    repository: "file://./charts/exporter-kube-scheduler/"

  - name: exporter-kube-state
    version: 0.0.1
    condition: exporter-kube-state.enabled
    repository: "file://./charts/exporter-kube-state/"

  - name: exporter-kubelets
    version: 0.0.1
    condition: exporter-kubelets.enabled
    repository: "file://./charts/exporter-kubelets/"

  - name: exporter-kubernetes
    version: 0.0.1
    condition: exporter-kubernetes.enabled
    repository: "file://./charts/exporter-kubernetes/"

  - name: exporter-node
    version: 0.0.1
    condition: exporter-node.enabled
    repository: "file://./charts/exporter-node/"

  - name: grafana
    version: 0.0.1
    condition: grafana.enabled
    repository: "file://./charts/grafana/"

  - name: prometheus
    version: 0.0.1
    condition: prometheus.enabled
    repository: "file://./charts/prometheus/"

  - name: metric-expression-project
    version: 0.0.1
    condition: metric-expression-project.enabled
    repository: "file://./charts/metric-expression-project/"

  - name: metric-expression-cluster
    version: 0.0.1
    condition: metric-expression-cluster.enabled
    repository: "file://./charts/metric-expression-cluster/"

  - name: exporter-fluentd
    version: 0.0.1
    condition: exporter-fluentd.enabled
    repository: "file://./charts/exporter-fluentd/"